import React from 'react'

function App() {
  return (
    <div className="app">
        <header className="App-header">
          <h1>React JS</h1>
            <h2>
              Edit <code>src/App.js</code> and save to reload.
            </h2>
            <a
              href="https://reactjs.org"
              target="_blank"
              rel="noopener noreferrer"
            >
              Learn React
            </a>
        </header>
        <div className="easy-project">
          <h4>This Project generated by <code>easy-project</code></h4>
        </div>
    </div>
  );
}

export default App;
